### ISSUE TITLE
Question about routes

### ISSUE THREAD

**Issue by Sekonda** [romegadigital/Multitenancy#16]
Hey,

I've only just started playing around with this package, so the answer might be obvious if I spent some more time. 

I've modified the login the controller so that it directs the user to their subdomain (assuming they only have one tenancy). 

How does routing work with this? E.g. if I called `route('dashboard')` for example, will that include their subdomain?

Sorry if the answer is obvious or I haven't spent enough time with it.

Thanks!

**Comment by ServerJunge** [comment]
Hello,

can you show me how you modified the login controller so that the user gets redirected to their subdomain after login?

**Comment by bradenkeith** [comment]
Hey everyone!

It's really simple actually - no modifications are necessary. The multitenancy auth middleware handles checking if the logged in user has access to the subdomain they're on. We aren't actively modifying anything with the login controller or caring how you are authenticating users. That's abstracted away from this package.

Basically you'll just need to send users to their correct routes before logging them in. ie:
suba.domain.com/login
subb.domain.com/login

Your controller is the same... once they login, protect your routes with the middleware and we'll check that the logged in user has access to the sub domain they're on.

Hope that helps.

I'll go ahead and get ahead of the next question - what if you have a single point of entry? That'll be up to you to figure out how you want to handle. Some considerations:
1) You'll have to change how your cookie saves so that they can stay authenticated once you forward them to their subdomain
2) Since a user can be a part of multiple subdomains in this package, you'll have to have some logic that either lets them choose which tenancy to forward them to or does this by some predetermined rule - both of which would be application specific.

Either way, you're not altering anything with your login controller. Once the user logins, you can access the tenants they have access to with `$user->tenants`

**Comment by bradenkeith** [comment]
The redirect for named routes will keep the subdomain intact.
